### ISSUE TITLE
Is there any reason behind yanking every version each time a new one is released?

### ISSUE THREAD

**Issue by jmg-duarte** [Lantern-chat/iso8601-timestamp#11]
Just as the title states, is there any reason?

When I reported https://github.com/Lantern-chat/iso8601-timestamp/issues/6 it made sense to me, as a bunch of older versions could be subject to a clearly breaking bug, but I've gone through the releases between 0.2.13 and 0.2.16 and none seem to fix a REALLY broken feature.

Constantly yanking the older versions "breaks" builds that depend on said version.
For example: https://github.com/Actyx/Actyx/issues/660

**Comment by novacrazy** [comment]
Apologies, I was unaware of that. Yes, just that and the missing feature flag thing were the main motivation, but probably overzealous. While I don't see any more reasons to continue yanking anyway, I'll certainly not now.

**Comment by jmg-duarte** [comment]
Thanks for the consideration! I'll be closing this then
