### ISSUE TITLE
Issue with UTC offsets

### ISSUE THREAD

**Issue by jmg-duarte** [Lantern-chat/iso8601-timestamp#6]
Hello! I'm not sure if this is a misinterpretation on my end of "(and automatically applying) UTC Offsets." or an actual bug so bear with me.

I have the following timestamp `2011-06-17T18:30+04:00`, this is a Dubai timezone, when converting to UTC, the proper time is: `2011-06-17T14:30:00.000000000Z`, however, the crate returns `2011-06-17T22:30:00.000000000Z`.

Minimal reproducible example:
```rust
fn main() {
    let ts = iso8601_timestamp::Timestamp::parse("2011-06-17T18:30+04:00");
    println!("{:?}", ts);        
}
```

**Comment by novacrazy** [comment]
Fixed in 0.2.13, had some logic reversed. Thanks for bringing this up!
