### ISSUE TITLE
How to convert a `Timestamp` into `SystemTime`?

### ISSUE THREAD

**Issue by Sajjon** [Lantern-chat/iso8601-timestamp#7]
Is it possible to convert `Timestamp` into `SystemTime`? Seems like [UniFFI](https://github.com/mozilla/uniffi-rs) works with `SystemTime` for binding to other languages, so even though my code uses `Timestamp` internally, for the UniFFI binding layer I need to convert the `Timestamp` into `SystemTime`.

**Comment by novacrazy** [comment]
`SystemTime::UNIX_EPOCH + your_timestamp.duration_since(Timestamp::UNIX_EPOCH)` would be the easiest way to convert them. I'll add a `From` impl soon that'll do that.

This operation can be quite inefficient given the different representations, though, so keep that in mind. 

EDIT: Added `From<Timestamp> for SystemTime` in `0.2.14`

**Comment by Sajjon** [comment]
Nice! Thanks!

**Comment by novacrazy** [comment]
Would it be useful for you to have `uniffi_core::FfiConverter` implemented for `Timestamp` instead? Likely more efficient than converting entirely to `SystemTime`. I've already prototyped it.

**Comment by novacrazy** [comment]
Huh, turns out there's a bug in uniffi's `SystemTime` handling where it'll lose precision between the unix epoch and one second before the unix epoch. Negative nanoseconds with zero whole seconds is unrepresentable.

**Comment by Sajjon** [comment]
@novacrazy yes that would be helpful!

I dont care a lot about precision for my particular usecase, so the bug you found will not affect me.

**Comment by novacrazy** [comment]
Going to go ahead and close this given the original issue is solved. More UniFFI stuff can be in #8
